# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c4d1ee799c81320c846edb196262c6627643435010cda36bf77661a7b7190fb68e41c2216f724250ca8f45b9568454d23db7e94cc65f08daa82117e3a30792b

test:
  secret_key_base: 2c46c1d79a901b4bb1d82aba7540aa3bf801614de613045f9136e6993383edf3b78e064b638ea25ba01f667811f322450d4fc72561a2605243b6b16e22a3433a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
